# Generated by Django 5.0.8 on 2025-02-04 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0002_sharedspace_owner'),
    ]

    operations = [
       
    ]
