# Generated by Django 5.2.7 on 2025-10-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('hub', '0011_profile_playground_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetWeekList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(verbose_name='Week')),
                ('week_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Weekly goal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetWeekListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cost')),
                ('cleared', models.BooleanField(default=False, verbose_name='Cost cleared')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetweeklist', verbose_name='Weekly budget')),
            ],
        ),
    ]
