# Generated by Django 5.2.7 on 2025-10-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetweeklistitem_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetweeklistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_items', to='budget.budgetweeklist', verbose_name='Weekly budget'),
        ),
    ]
