# Generated by Django 5.2.7 on 2025-10-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_budgetweeklistitem_list'),
        ('space', '0005_sharedspace_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetweeklist',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.sharedspace', verbose_name='Space'),
        ),
    ]
