[uwsgi]
socket = 127.0.0.1:5001
chdir=/code
module=root.wsgi:application
master=True
pidfile=/tmp/project-master.pid
vacuum=True
max-requests=5000
; daemonize=/var/log/uwsgi/household.log
processes = 4
threads = 2
harakiri = 30
harakiri-verbose = true
die-on-term = true
lazy-apps = true
need-plugin = python3
single-interpreter = true
stats = 127.0.0.1:9191

