services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
    web:
        build: .
        # command: python manage.py runserver 0.0.0.0:42069
        entrypoint: bash test_startup.sh
        volumes:
            - .:/code
        ports:
            - "42069:42069"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_EMAIL=root@root.org
            - DJANGO_SUPERUSER_PASSWORD=admin
        depends_on:
            - db