services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - config.env
        ports:
            - "5432:5432"
        restart: always
        networks:
          - net
    web:
        build: .
        volumes:
            - ./_logs/supervisor:/var/log/supervisor
            - ./_logs/nginx:/var/log/nginx
            - ./_logs/uwsgi:/var/log/uwsgi
            - ./_logs/django:/var/log/django
            - ./_logs/celery_beat:/var/log/celery_beat
            - ./_logs/celery_worker:/var/log/celery_worker
            - ./_logs/redis:/var/log/redis
        ports:
            - "5000:5000"
        env_file:
            - config.env
        depends_on:
            - db
        networks:
            - net
            - redis-net
        restart: always
    redis:
        image: redis:8.0.2
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes: 
            - ./redis_cache:/data
        networks:
            - redis-net
networks:
  net:
    external: true
  redis-net:
    external: false
