[program:nginx]
command=bash /code/docker/nginx/run_nginx.sh
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/nginx/stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/nginx/stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3

[program:uwsgi]
command=bash /code/docker/uwsgi/run_uwsgi.sh
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/uwsgi/stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/uwsgi/stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3

[program:celery_worker]
command=bash /code/docker/celery_worker/run_celery.sh
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/celery_worker/stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/celery_worker/stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3

[program:celery_beat]
command=bash /code/docker/celery_beat/run_beat.sh
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/celery_beat/stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/celery_beat/stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3