[program:nginx]
command=bash /code/docker/nginx/run_nginx.sh
stdout_logfile=/var/log/nginx/stdout.log
stderr_logfile=/var/log/nginx/stderr.log

[program:uwsgi]
command=bash /code/docker/uwsgi/run_uwsgi.sh
stdout_logfile=/var/log/uwsgi/stdout.log
stderr_logfile=/var/log/uwsgi/stderr.log