# Generated by Django 5.0.7 on 2024-08-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='position',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
