# Generated by Django 5.0.7 on 2024-08-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='todo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todos.todo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubTaskToTodo',
        ),
    ]
