# Generated by Django 5.0.8 on 2024-08-07 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_user_selected_space'),
        ('todos', '0005_subtask_todo_delete_subtasktotodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='space',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hub.sharedspace'),
            preserve_default=False,
        ),
    ]
