# Generated by Django 5.0.8 on 2024-08-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
        ('todos', '0006_todo_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.sharedspace'),
        ),
    ]
