# Generated by Django 5.0.8 on 2024-09-20 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_alter_user_selected_space'),
        ('todos', '0008_todo_assigned_user_ordereduser_todorecurrency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereduser',
            name='empty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordereduser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.user'),
        ),
    ]
