# Generated by Django 5.0.8 on 2024-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_ordereduser_empty_alter_ordereduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todorecurrency',
            name='started_at',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
