# Generated by Django 5.0.8 on 2024-10-03 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_todorecurrency_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todorecurrency',
            name='last_check',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
