# Generated by Django 5.0.8 on 2024-10-03 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_todorecurrency_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todorecurrency',
            name='started_at',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
