# Generated by Django 5.0.8 on 2025-05-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_remove_user_auth_user_remove_user_selected_space_and_more'),
        ('todos', '0012_alter_todorecurrency_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereduser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.profile'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.profile'),
        ),
        migrations.AlterField(
            model_name='todorecurrency',
            name='assigned_users',
            field=models.ManyToManyField(through='todos.OrderedUser', to='hub.profile'),
        ),
    ]
