# Generated by Django 5.2 on 2025-05-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_delete_user'),
        ('todos', '0013_alter_ordereduser_user_alter_todo_assigned_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoRecurrency',
            new_name='TodoSchedule',
        ),
        migrations.RenameField(
            model_name='ordereduser',
            old_name='recurrent_todo',
            new_name='scheduled_todo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='recurrent_state',
            new_name='schedule_state',
        ),
        migrations.RenameField(
            model_name='todoschedule',
            old_name='recurrency_turn',
            new_name='schedule_turn',
        ),
    ]
