# Generated by Django 5.2.1 on 2025-05-30 20:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_alter_profile_selected_space_alter_profile_spaces_and_more'),
        ('space', '0004_alter_sharedspace_invite_token_and_more'),
        ('todos', '0014_rename_todorecurrency_todoschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereduser',
            name='empty',
            field=models.BooleanField(default=False, verbose_name='Empty'),
        ),
        migrations.AlterField(
            model_name='ordereduser',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='ordereduser',
            name='scheduled_todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.todoschedule', verbose_name='Todo Schedule'),
        ),
        migrations.AlterField(
            model_name='ordereduser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.profile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.todo', verbose_name='Todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.profile', verbose_name='Assigned user'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='position',
            field=models.IntegerField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='schedule_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.todoschedule', verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.sharedspace', verbose_name='Space'),
        ),
        migrations.AlterField(
            model_name='todoschedule',
            name='assigned_users',
            field=models.ManyToManyField(through='todos.OrderedUser', to='hub.profile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='todoschedule',
            name='day_rotation',
            field=models.IntegerField(default=7, verbose_name='Day rotation'),
        ),
        migrations.AlterField(
            model_name='todoschedule',
            name='last_check',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Last check'),
        ),
        migrations.AlterField(
            model_name='todoschedule',
            name='schedule_turn',
            field=models.IntegerField(default=0, verbose_name='Schedule Turn'),
        ),
        migrations.AlterField(
            model_name='todoschedule',
            name='started_at',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now, verbose_name='Started at'),
        ),
    ]
