# Generated by Django 5.0.7 on 2024-07-16 15:42

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('currency', models.CharField(choices=transactions.models.get_currencies, default='EUR', max_length=3)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
