# Generated by Django 5.0.8 on 2024-08-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='My Shared Living Space', max_length=100)),
                ('invite_token', models.TextField(max_length=10)),
            ],
        ),
    ]
