# Generated by Django 5.0.8 on 2024-09-06 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_alter_user_spaces'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedspace',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.user'),
        ),
    ]
