# Generated by Django 5.0.8 on 2025-05-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_remove_user_auth_user_remove_user_selected_space_and_more'),
        ('space', '0002_sharedspace_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedspace',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.profile'),
        ),
    ]
