# Generated by Django 5.2.1 on 2025-05-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_alter_profile_selected_space_alter_profile_spaces_and_more'),
        ('space', '0003_alter_sharedspace_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedspace',
            name='invite_token',
            field=models.TextField(max_length=10, verbose_name='Invite Token'),
        ),
        migrations.AlterField(
            model_name='sharedspace',
            name='name',
            field=models.TextField(default='My Space', max_length=100, verbose_name='Space name'),
        ),
        migrations.AlterField(
            model_name='sharedspace',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.profile', verbose_name='Owner'),
        ),
    ]
