# Generated by Django 5.2.2 on 2025-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_alter_sharedspace_invite_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedspace',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked'),
        ),
    ]
