# Generated by Django 5.2.15 on 2026-07-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_sharedspace_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedspace',
            name='name',
            field=models.CharField(default='My Space', max_length=100, verbose_name='Space name'),
        ),
    ]
