# Generated by Django 5.0.8 on 2024-08-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_user_selected_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='selected_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_space', to='hub.sharedspace'),
        ),
    ]
