# Generated by Django 5.0.8 on 2024-08-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_user_selected_space'),
        ('space', '0001_initial'),
        ('todos', '0007_alter_todo_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='selected_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_space', to='space.sharedspace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='spaces',
            field=models.ManyToManyField(to='space.sharedspace'),
        ),
        migrations.DeleteModel(
            name='SharedSpace',
        ),
    ]
