# Generated by Django 5.0.8 on 2024-08-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_user_selected_space_alter_user_spaces_and_more'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spaces',
            field=models.ManyToManyField(blank=True, null=True, to='space.sharedspace'),
        ),
    ]
