# Generated by Django 5.0.8 on 2024-08-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_alter_user_spaces'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spaces',
            field=models.ManyToManyField(to='space.sharedspace'),
        ),
    ]
