# Generated by Django 5.0.8 on 2024-09-06 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_alter_user_spaces'),
        ('space', '0002_sharedspace_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='selected_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_space', to='space.sharedspace'),
        ),
    ]
