# Generated by Django 5.0.8 on 2025-05-26 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_alter_user_selected_space'),
        ('space', '0002_sharedspace_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='selected_space',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spaces',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_space', to='space.sharedspace')),
                ('spaces', models.ManyToManyField(to='space.sharedspace')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
