# Generated by Django 5.0.8 on 2025-05-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_remove_user_auth_user_remove_user_selected_space_and_more'),
        ('space', '0003_alter_sharedspace_owner'),
        ('todos', '0013_alter_ordereduser_user_alter_todo_assigned_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
