# Generated by Django 5.2.1 on 2025-05-30 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_delete_user'),
        ('space', '0003_alter_sharedspace_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_space', to='space.sharedspace', verbose_name='Selected Space'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spaces',
            field=models.ManyToManyField(to='space.sharedspace', verbose_name='Spaces'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auth user'),
        ),
    ]
