# Generated by Django 5.2.2 on 2025-06-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_alter_profile_selected_space_alter_profile_spaces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='playground_account',
            field=models.BooleanField(default=False, verbose_name='Playground Account'),
        ),
    ]
