# Generated by Django 5.0.8 on 2025-02-04 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0007_alter_user_selected_space'),
        ('space', '0002_sharedspace_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.sharedspace', verbose_name='Space')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItemOnList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Amount')),
                ('checked', models.BooleanField(default=False, verbose_name='Bought')),
                ('bought_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.user')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppingitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(through='shopping.ShoppingItemOnList', to='shopping.shoppingitem', verbose_name='Items')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.sharedspace', verbose_name='Space')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingitemonlist',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppinglist'),
        ),
    ]
